### ISSUE TITLE
My publish is failing but I'm really not sure why

### ISSUE THREAD

**Issue by devedse** [isaacrlevin/windows-store-action#5]
I've added the publish command but it keeps failing and I'm not sure why:

https://github.com/devedse/DeveBlockStacker/runs/5805644843?check_suite_focus=true

Here's the github actions file I'm using:
https://github.com/devedse/DeveBlockStacker/blob/1.0.154/.github/workflows/githubactionsbuilds.yml#L464

Do you have any idea what I could be doing wrong?

**Comment by jankratochvilcz** [comment]
I'm having the same issue 👍

* [Action YAML](https://github.com/jankratochvilcz/kotobaten-flutter/blob/main/.github/workflows/deploy.yml#L102)
* [Action run](https://github.com/jankratochvilcz/kotobaten-flutter/runs/5806403930?check_suite_focus=true)

**Comment by jankratochvilcz** [comment]
Solved 🙌 I was putting in the wrong ID

![image](https://user-images.githubusercontent.com/2202487/161435812-bdfc4ee7-69e8-4a09-9c01-d2502913779a.png), it's supposed to be _Store ID_, not the _Package ID_

**Comment by devedse** [comment]
This fixed the issue for me too. I assumed that `DeveBlockStacker` would be fine, but apparently it had to be the store_id as you showed in your screenshot. It might be good to update the documentation though:
![image](https://user-images.githubusercontent.com/2350015/161443593-6acdf839-2737-4ef1-9948-977e2588c6a8.png)

**Comment by devedse** [comment]
I do run into some issues though if I try to submit a new version of a package that's still being verified:
```
message: 'Create submission failed, status code Conflict, reason phrase Conflict',
```

https://github.com/devedse/DeveBlockStacker/runs/5808358681?check_suite_focus=true

Is there anything we can do about that?

**Comment by jankratochvilcz** [comment]
There is `delete-pending` https://github.com/isaacrlevin/windows-store-action/blob/main/action.yml#L17, but unsure if it'll work if the submission is already being reviewed.

Btw. I'm not a maintainer of the project. I did a few fix-up PRs to see what if this project is maintained or not. I'm happy to contribute here, or fork the project and maintain it as it's relatively straightforward and very useful.

**Comment by devedse** [comment]
It seems the default value for `delete-pending` is `true`. So it should already work then right?

**Comment by jankratochvilcz** [comment]
Yup 🤷‍♂️. This said, it doesn't work for me either

**Comment by isaacrlevin** [comment]
I typically delete any pending before I republish, but would gladly accept a PR to check for a 409 and ask to rewrite or whatever.
